# Generated by Django 5.1.6 on 2025-02-18 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_employees_project_employess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='employess',
            new_name='employees',
        ),
    ]
